version: '3'

services:
  web:
    build: docker/web
    container_name: web
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/milk-tea
    links:
      - db
    command: sh /entry-point.sh

  db:
    image: mysql:5.7
    container_name: milk-tea-db
    hostname: milk-tea-db
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=milk-tea
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: php-myadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1

  nodejs:
    container_name: nodejs
    tty: true
    stdin_open: true
    build: ./docker/nodejs
#      command: bash /docker-entrypoint.sh
    volumes:
      - .:/home/node/app
